apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: uj205xsmu-nodejs-gitops
  description: This is GitOps manifest for uj205xsmu-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=uj205xsmu-nodejs
    backstage.io/kubernetes-id: uj205xsmu-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: uj205xsmu-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:uj205xsmu-nodejs
