apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: uj205xsmu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: uj205xsmu-nodejs 
  name: uj205xsmu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: uj205xsmu-nodejs 
